name: Build Xiaomi Mi 8 SE (Sirius) crDroid A14

on:
  workflow_call:
  workflow_dispatch:

env:
  # ===== Device env =====
  DEVICE_NAME: "Xiaomi_Mi_8_SE"
  DEVICE_CODENAME: "sirius"

  # ===== 编译参数（修正版）=====
  CUSTOM_CMDS: ""
  EXTRA_CMDS: ""

  # ===== Kernel =====
  KERNEL_SOURCE: "https://github.com/Rocky7842/android_kernel_xiaomi_sdm710.git"
  KERNEL_BRANCH: "lineage-23.2-ksu"

  # ===== Clang（可选，默认关闭）=====
  CLANG_SOURCE: ""
  CLANG_BRANCH: ""

  # ===== GCC（必须）=====
  GCC_GNU: true
  GCC_64_SOURCE: "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9"
  GCC_64_BRANCH: "android12L-release"
  GCC_32_SOURCE: "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9"
  GCC_32_BRANCH: "android12L-release"

  # ===== Defconfig =====
  DEFCONFIG_NAME: "sdm670-perf_defconfig"

  # ===== KernelSU =====
  KERNELSU_AUTO_GET: "true"
  KERNELSU_AUTO_FORK: "resukisu"

  # ===== 功能开关 =====
  SUSFS_ENABLE: false
  REKERNEL_ENABLE: "false"
  KPM_ENABLE: "false"
  BASEBAND_GUARD_ENABLE: "false"

  # ===== Packing =====
  PACK_METHOD: "Anykernel3"
  PACK_KMODULES: "false"
  AK3_SOURCE: "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH: "master"

  # ===== Misc =====
  BUILD_OTHER_CONFIG: true
  MERGE_CONFIG_FILES: "xiaomi/sdm710-common.config"
  FREE_MORE_SPACE: true
  BUILD_DEBUGGER: true
  SKIP_PATCH: false

jobs:
  build-kernel:
    name: Xiaomi Mi 8 SE (Sirius)
    runs-on: ubuntu-latest
    container: ubuntu:focal

    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout
        uses: actions/checkout@v6

      - name: ⌛️ Build environment
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get tools
        uses: ./.github/workflows/build-ready

      - name: 🪛 Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          ./scripts/config --file out/.config \
            -d CONFIG_VDSO \
            -d CONFIG_COMPAT_VDSO \
            -d CONFIG_KPROBES \
            -d CONFIG_UPROBES
          make O=out olddefconfig

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
